In [2]:
import pandas as pd

In [2]:
df = pd.read_csv('sample.csv')

In [3]:
df

   id            name  age          city                    email
0   1      John Smith   28      New York   john.smith@example.com
1   2    Emma Johnson   34   Los Angeles       emma.j@example.com
2   3   Michael Brown   45       Chicago       mbrown@example.com
3   4     Sarah Davis   22       Houston  sarah.davis@example.com
4   5    David Wilson   31       Phoenix      dwilson@example.com
5   6  Laura Martinez   27  Philadelphia    lmartinez@example.com
6   7  James Anderson   39   San Antonio    janderson@example.com
7   8   Olivia Taylor   25     San Diego      otaylor@example.com

In [4]:
df.shape

(8, 5)

In [5]:
type(df.shape)

tuple

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      8 non-null      int64
 1   name    8 non-null      str
 2   age     8 non-null      int64
 3   city    8 non-null      str
 4   email   8 non-null      str
dtypes: int64(2), str(3)
memory usage: 784.0 bytes

In [3]:
# Create a Series from a list
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
df.head()

   id           name  age         city                    email
0   1     John Smith   28     New York   john.smith@example.com
1   2   Emma Johnson   34  Los Angeles       emma.j@example.com
2   3  Michael Brown   45      Chicago       mbrown@example.com
3   4    Sarah Davis   22      Houston  sarah.davis@example.com
4   5   David Wilson   31      Phoenix      dwilson@example.com

In [4]:
s[2]

np.int64(30)

In [5]:
print(s[2])

30

In [6]:
print(s.iloc[3])

40

In [7]:
print(s[1:4])

1    20
2    30
3    40
dtype: int64

In [3]:
# Creating a DataFrame from a dictionary
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}

In [4]:
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [10]:
df.iloc[2]

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object

In [5]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [6]:
print(df['City'])

0         New York
1    San Francisco
2      Los Angeles
3          Chicago
Name: City, dtype: str

In [8]:
print(df.iloc[2]) 
print()# Access the third row by position
print(df.loc[1])    # Access the second row by label

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object

Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

## In short, you can do anything with data using pandas

In [9]:
df = pd.read_excel('student_info.xlsx')

In [10]:
df

,Team No.,Timestamp,Team Leader Name,Team Leader Email,Team Leader Enrolment Number,Team Leader Student Branch,Team Leader Division,Team Leader Roll No.,Team Leader Contact Number,Internal Guide Name (Selected on DE Portal as per given in shared sheet),No. of Team Members,Team Members Names (Write names of Team member by seperating names with comma),Team Members Contact No. (Write Contact numbers of first Team member),Team Members Email Address (Give email ID of first team member),Project Title (Name of project on De portal),Project Title Description (Short Decription explaining your project),Team Status
0,1,2026-02-13 11:08:59.553000,Yug Shah,yugshah180907@gmail.com,251430131175,CSE,D6,193,7600182676,APR,5,"Gami Meet, Patel Dhyan , Ramani Khush , Pandya...",9274320741,meetgami33@gmail.com,UPI & Online fraud,Awareness and different ways how people get sc...,Complete Team Approved (Full group with all me...
1,2,2026-02-13 11:11:04.628000,BUSA TEERTH NARENDRABHAI,teerth2307@gmail.com,251430131011,CSE,D2,41,8160579939,APR,5,"PATEL VISHV AJITBHAI, PATEL VANSH RAJESHBHAI, ...",6353592681991310275050726287352902189056,ajitpatel5088@gmail.com,Railway Station Management System,Railway Station. This domain is analyzed throu...,Complete Team Approved (Full group with all me...
2,3,2026-02-13 11:15:16.420000,Yatri Raval,yatriraval7@gmail.com,251430131208,CSE,D5,146,70187 84617,VBP,5,"Mana Mayurkumar Patel, Sarchi Dhavalkumar Pate...","7016055456, 9723770407,9714946404,8154039958","manapatel0754@gmail.com, patelsarchi3@gmail.c...",Urban Ease,Moving to new city and looking for home away f...,1 member left
3,4,2026-02-13 11:16:31.414000,Thakkar Pankti Bhaveshkumar,panktit13@gmail.com,251430131199,CSE,D1,25,9724345529,MJP,6,"Thakkar khushi Anilkumar, Darji Shruti Mayankk...",9328230237,thakkarkhushi303@gmail.com,Digital fraud,•\tOne-tap fraud reporting\n\t•\tEvidence capt...,1 member left
4,5,2026-02-13 11:17:05.969000,Choksi khushil brijesh,khushilchoksi77@gmail.com,251430142019,CSE(AIML),D8,43,9499509654,DPP,6,"Yash trivedi, kathan vadgana, nishil patel, di...",6355090829905480186683949580326165004721672578...,trivedijigar507@gmail.com,Smart traffic management,An intelligent AI driven network using iot sen...,Complete Team Approved (Full group with all me...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,2/16/2026 11:23:00,Kukadiya Manav Rajeshbhai,manavkukadiya46@gmail.com,251430142073,CSE(AIML),D11,154,7383231534,DCB,6,"Vaghela Dhruv Hirenbhai, Sankadasariya Naitik ...","8485969008, 8128582008","dhruvvaghela138@gmail.com,naitik6480@gmail.com...",Smart classroom lighting System,Smart Classroom LightingThese systems typicall...,Complete Team Approved (Full group with all me...
89,90,2/16/2026 11:23:39,Jay Rajeshbhai Gulvani,jaygulvani4@gmail.com,251430142043,CSE(AIML),D10,112,9327476376,JST,5,"Kalal Nayank narayanbhai,Ansh Shrinivas manchi...",9558247223879939973655450992687353692160,"nayankkalal5@gmail.com, anshmanchikatla9@gmail...",AXON,This project is a Multi-Sector Intelligent Sug...,Complete Team Approved (Full group with all me...
90,91,2/16/2026 11:24:27,Lukhi Devam Mukeshbhai,devamlukhi358@gmail.com,251430131066,CSE,D5,170,8799324653,VPS,4,"Hirapara Hetkumar Kamleshbhai,\nSuvagiya Ansh ...","8799247948, 9428028696, 886676129","hethirapara5086@gmail.com, arsuvagiya2007@gmai...",A Design thinking approach to smart airport sy...,A compiled report of the Problems we observed ...,Complete Team Approved (Full group with all me...
91,92,2/16/2026 14:02:57,Hetav Brijeshkumar Solanki,hetavsolanki781@gmail.com,251430142046,CSE(AIML),D12,196,8401986450,SST,6,"PUROHIT JAYESH LAVJIBHAI,CHAUDHARY MAHIR SANJA...",8849038278834709843096161098576661648656405259...,"yogeshpurohit5566@gmail.com,mahirchaudhary182@...",Smart CrowdSense – AI Based Public Transport C...,Smart CrowdSense is an AI-based public transpo...,Complete Team Approved (Full group with all me...
92,93,NaN,Momin Munirahbanu zahirahemad.,Pasand3486@gmail.com,251430142094,CSE(AIML),D11,134,9898304844,JDP,6,"shraddha,jinal,jency,punit,dhruv",9687326214,jency.goswami08@gmail.com,smart safety alert,smart safety alert is a smart system that show...,Complete Team Approved (Full group with all me...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 17 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Team No.                                                                        93 non-null     int64
 1   Timestamp                                                                       89 non-null     object
 2   Team Leader Name                                                                93 non-null     str
 3   Team Leader Email                                                               93 non-null     str
 4   Team Leader Enrolment Number                                                    93 non-null     int64
 5   Team Leader  Student Branch                                                     93 non-null     str
 6   Team Leader  Division                                                           93 non-null     str
 7   Team Leader  Roll No.                                                           93 non-null     int64
 8   Team Leader  Contact Number                                                     93 non-null     object
 9   Internal Guide Name (Selected on DE Portal as per given in shared sheet)        93 non-null     str
 10  No. of Team Members                                                             93 non-null     int64
 11  Team Members Names (Write names of Team member by seperating names with comma)  93 non-null     str
 12  Team Members Contact No.  (Write Contact numbers of first Team member)          93 non-null     object
 13  Team Members Email Address (Give email ID of first team member)                 93 non-null     str
 14  Project Title (Name of project on De portal)                                    93 non-null     str
 15  Project Title Description (Short Decription explaining your project)            93 non-null     str
 16  Team Status                                                                     93 non-null     str
dtypes: int64(4), object(3), str(10)
memory usage: 71.6+ KB

In [13]:
df[['Team Leader Name', 'Team Leader Email']]

                  Team Leader Name          Team Leader Email
0                        Yug Shah     yugshah180907@gmail.com
1         BUSA TEERTH NARENDRABHAI       teerth2307@gmail.com
2                      Yatri Raval      yatriraval7@gmail.com
3      Thakkar Pankti Bhaveshkumar        panktit13@gmail.com
4           Choksi khushil brijesh  khushilchoksi77@gmail.com
..                             ...                        ...
88       Kukadiya Manav Rajeshbhai  manavkukadiya46@gmail.com
89          Jay Rajeshbhai Gulvani      jaygulvani4@gmail.com
90          Lukhi Devam Mukeshbhai    devamlukhi358@gmail.com
91      Hetav Brijeshkumar Solanki  hetavsolanki781@gmail.com
92  Momin Munirahbanu zahirahemad.       Pasand3486@gmail.com

[93 rows x 2 columns]

In [15]:
# Get rows where Name contains 'li' (like Alice or Charlie)
rows = df.loc[df['Team Leader Name'].str.contains('Shrey')]
rows

,Team No.,Timestamp,Team Leader Name,Team Leader Email,Team Leader Enrolment Number,Team Leader Student Branch,Team Leader Division,Team Leader Roll No.,Team Leader Contact Number,Internal Guide Name (Selected on DE Portal as per given in shared sheet),No. of Team Members,Team Members Names (Write names of Team member by seperating names with comma),Team Members Contact No. (Write Contact numbers of first Team member),Team Members Email Address (Give email ID of first team member),Project Title (Name of project on De portal),Project Title Description (Short Decription explaining your project),Team Status
39,40,2026-02-13 23:39:29.080000,Shrey Pranav Modh,modhshrey@gmail.com,251430131072,CSE,D2,52,6354075497,KJP,6,"Dhairya Shankarbhai Gajjar,\nKrish Harneshbhai...","8160318682, 8128320536, 9016860869, 9664843794...","dhairyasgajjar24@gmail.com, upadhyaykrish207@g...",Student Career Guidance System,"> The Practical Problem: Engineering students,...",Complete Team Approved (Full group with all me...

In [16]:
type(rows)

pandas.DataFrame

In [26]:
rows.iloc[0,11]

'Dhairya Shankarbhai Gajjar,\nKrish Harneshbhai Upadhyay, \nShail Chiragkumar Thaker, \nOm Mahesh Patel,\nAnsh Pinakin Patel'